#pragma once

enum class FightPhase {
  PLAYER_CHOICE,
  DEBUFF_CHOICE,
  PRE_QTE,
  PLAYER_QTE,
  RESOLUTION_PLAYER,
  WAITING_AFTER_PLAYER,
  PLAYER_DEFENSE_QTE,
  RESOLUTION_ENEMY,
  WAITING_AFTER_ENEMY
};

enum class FightTrigger {
  CHOOSE_STRENGTH,
  CHOOSE_ELOQUENCE,
  CHOOSE_DEBUFF_ATTACK,
  CHOOSE_DEBUFF_DEFENSE,
  START_QTE,
  FINISH_QTE,
  FINISH_TEXT_QTE,
  START_ENEMY_TURN,
  START_DEFENSE_QTE,
  FINISH_DEFENSE_QTE,
  FINISH_ENEMY_TURN,
  NEXT_PLAYER_TURN,
  CANCEL
};